# Generated by Django 4.2.9 on 2024-07-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')])),
                ('age', models.IntegerField()),
                ('marital_status', models.IntegerField(choices=[(0, 'Single'), (1, 'Married')])),
                ('anxiety', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('panic_attack', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('specialist_treatment', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('year_of_study', models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4')])),
                ('knn_prediction', models.IntegerField(blank=True, null=True)),
                ('decision_tree_prediction', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
